In [251]:
import pandas as pd
import numpy as np
import plotly.express as px

## Loading Data

In [26]:
df = pd.read_csv('direct_mail_campaign.csv')

In [68]:
#Checking datattypes of every column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 18 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   prospect_id                          50000 non-null  object
 1   industry                             50000 non-null  object
 2   business_size                        50000 non-null  object
 3   region                               50000 non-null  object
 4   offer_type                           50000 non-null  object
 5   acquisition_channel                  50000 non-null  object
 6   credit_score_band                    50000 non-null  object
 7   years_in_business                    50000 non-null  object
 8   mailer_sent_date                     50000 non-null  datetime64[ns]
 9   response_date                        1618 non-null   datetime64[ns]
 10  response_flag                        50000 non-null  int64
 11  acquisition_flag                     50000 non-null  int64
 12  mailing_cost_usd                     50000 non-null  float64
 13  estimated_monthly_charge_volume_usd  50000 non-null  float64
 14  roi                                  50000 non-null  float64
 15  cost_per_acquisition                 1040 non-null   float64
 16  prospect_value_tier                  50000 non-null  object
 17  days_to_respond                      1618 non-null   timedelta64[ns]
dtypes: datetime64[ns](2), float64(4), int64(2), object(9), timedelta64[ns](1)
memory usage: 6.9+ MB

In [69]:
#Looking at statistics of the data
df.describe()

,mailer_sent_date,response_date,response_flag,acquisition_flag,mailing_cost_usd,estimated_monthly_charge_volume_usd,roi,cost_per_acquisition,days_to_respond
count,50000,1618,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,1040.000000,1618
mean,2024-01-01 13:21:19.872000,2024-01-16 17:42:38.714462464,0.032360,0.020800,1.949399,429.989170,3.572350,1.923308,18 days 13:56:35.302843016
min,2023-01-01 00:00:00,2023-01-10 00:00:00,0.000000,0.000000,1.570000,0.000000,-1.000000,1.570000,7 days 00:00:00
25%,2023-07-02 00:00:00,2023-07-21 00:00:00,0.000000,0.000000,1.750000,0.000000,-1.000000,1.770000,12 days 00:00:00
50%,2024-01-03 00:00:00,2024-01-13 12:00:00,0.000000,0.000000,1.950000,0.000000,-1.000000,1.910000,19 days 00:00:00
75%,2024-07-03 00:00:00,2024-07-19 00:00:00,0.000000,0.000000,2.140000,0.000000,-1.000000,2.050000,25 days 00:00:00
max,2024-12-31 00:00:00,2025-01-26 00:00:00,1.000000,1.000000,2.360000,177640.120000,2006.943700,2.360000,30 days 00:00:00
std,NaN,NaN,0.176956,0.142716,0.219976,5459.832174,59.094608,0.197446,6 days 23:33:18.321567464

In [ ]:
#Checking for duplicated prodpect IDs
df['prospect_id'].duplicated().value_counts()

prospect_id
False    50000
Name: count, dtype: int64

In [ ]:
#Counting number of propects who responded to the mail
df['response_date'].isnull().value_counts()

response_date
True     48382
False     1618
Name: count, dtype: int64

In [46]:
#Checking null values in columns
for col in df.columns:
    print(df[col].isnull().value_counts())
    print('')
    print('==================================================')

prospect_id
False    50000
Name: count, dtype: int64

==================================================
industry
False    50000
Name: count, dtype: int64

==================================================
business_size
False    50000
Name: count, dtype: int64

==================================================
region
False    50000
Name: count, dtype: int64

==================================================
offer_type
False    50000
Name: count, dtype: int64

==================================================
acquisition_channel
False    50000
Name: count, dtype: int64

==================================================
credit_score_band
False    50000
Name: count, dtype: int64

==================================================
years_in_business
False    50000
Name: count, dtype: int64

==================================================
mailer_sent_date
False    50000
Name: count, dtype: int64

==================================================
response_date
True     48382
False     1618
Name: count, dtype: int64

==================================================
response_flag
False    50000
Name: count, dtype: int64

==================================================
acquisition_flag
False    50000
Name: count, dtype: int64

==================================================
mailing_cost_usd
False    50000
Name: count, dtype: int64

==================================================
estimated_monthly_charge_volume_usd
False    50000
Name: count, dtype: int64

==================================================
roi
False    50000
Name: count, dtype: int64

==================================================
cost_per_acquisition
True     48960
False     1040
Name: count, dtype: int64

==================================================
prospect_value_tier
False    50000
Name: count, dtype: int64

==================================================

In [54]:
#Changing Datatypes

df['prospect_id'] = df['prospect_id'].astype('str')
df['mailer_sent_date'] = pd.to_datetime(df['mailer_sent_date'])
df['response_date'] = pd.to_datetime(df['response_date'])

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 17 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   prospect_id                          50000 non-null  object
 1   industry                             50000 non-null  object
 2   business_size                        50000 non-null  object
 3   region                               50000 non-null  object
 4   offer_type                           50000 non-null  object
 5   acquisition_channel                  50000 non-null  object
 6   credit_score_band                    50000 non-null  object
 7   years_in_business                    50000 non-null  object
 8   mailer_sent_date                     50000 non-null  datetime64[ns]
 9   response_date                        1618 non-null   datetime64[ns]
 10  response_flag                        50000 non-null  int64
 11  acquisition_flag                     50000 non-null  int64
 12  mailing_cost_usd                     50000 non-null  float64
 13  estimated_monthly_charge_volume_usd  50000 non-null  float64
 14  roi                                  50000 non-null  float64
 15  cost_per_acquisition                 1040 non-null   float64
 16  prospect_value_tier                  50000 non-null  object
dtypes: datetime64[ns](2), float64(4), int64(2), object(9)
memory usage: 6.5+ MB

In [ ]:
#Creating new column for days it took to response
df['days_to_respond'] = df['response_date'] - df['mailer_sent_date']

In [67]:
#Sanity check for ROI to be 0 for only those rows where acquisition flag was 0
df[df['roi'] == -1]['acquisition_flag'].value_counts()

acquisition_flag
0    48960
Name: count, dtype: int64

## Response and Acquisition Analysis

In [ ]:
#Overall Response rate
df['response_flag'].sum()/len(df)

np.float64(0.03236)

In [78]:
#Overall Acquisition Rate
df['acquisition_flag'].sum()/len(df)

np.float64(0.0208)

In [79]:
df.head()

,prospect_id,industry,business_size,region,offer_type,acquisition_channel,credit_score_band,years_in_business,mailer_sent_date,response_date,response_flag,acquisition_flag,mailing_cost_usd,estimated_monthly_charge_volume_usd,roi,cost_per_acquisition,prospect_value_tier,days_to_respond
0,100000,Education,Medium (50-249),Midwest,No Annual Fee,Lookalike Audience,700-749,1-3 yrs,2024-10-16,NaT,0,0,1.64,0.0,-1.0000,NaN,Not Acquired,NaT
1,100001,Technology,Micro (1-9),Southeast,Travel Miles 2x,Partner Referral,600-649,7-15 yrs,2023-04-25,2023-05-02,1,1,2.28,465.9,3.0868,2.28,Low Value,7 days
2,100002,Real Estate,Micro (1-9),Southwest,0% Intro APR,Cold List,750-799,3-7 yrs,2023-10-09,NaT,0,0,2.02,0.0,-1.0000,NaN,Not Acquired,NaT
3,100003,Healthcare,Large (250+),Southwest,Rewards Points 3x,Cold List,750-799,7-15 yrs,2023-09-08,NaT,0,0,2.05,0.0,-1.0000,NaN,Not Acquired,NaT
4,100004,Hospitality,Micro (1-9),Northeast,Travel Miles 2x,Cold List,700-749,<1 yr,2023-08-17,NaT,0,0,2.18,0.0,-1.0000,NaN,Not Acquired,NaT

In [ ]:
#Calculating response rate for each offer type
(df.groupby('offer_type')['response_flag'].sum()/len(df)).sort_values(ascending=False)\
    .reset_index()\
    .rename(columns={'response_flag': 'response_rate'})

          offer_type  response_rate
0       0% Intro APR        0.00916
1       Cash Back 2%        0.00722
2      No Annual Fee        0.00586
3  Rewards Points 3x        0.00548
4    Travel Miles 2x        0.00464

In [ ]:
#Calculating Acquisition rate for each offer type
(df.groupby('offer_type')['acquisition_flag'].sum()/len(df)).sort_values(ascending=False)\
    .reset_index()\
    .rename(columns={'acquisition_flag': 'acquisition_rate'})

          offer_type  acquisition_rate
0       0% Intro APR           0.00610
1       Cash Back 2%           0.00484
2      No Annual Fee           0.00376
3  Rewards Points 3x           0.00334
4    Travel Miles 2x           0.00276

In [ ]:
#Calculating response rate for each industry
(df.groupby('industry')['response_flag'].sum()/len(df)).sort_values(ascending=False)\
    .reset_index()\
    .rename(columns={'response_flag': 'response_rate'})

        industry  response_rate
0     Healthcare        0.00374
1   Construction        0.00366
2    Real Estate        0.00348
3         Retail        0.00346
4  Manufacturing        0.00330
5      Logistics        0.00330
6     Technology        0.00318
7    Hospitality        0.00302
8        Finance        0.00286
9      Education        0.00236

In [ ]:
#Calculating Acquisition rate for each industry
(df.groupby('industry')['acquisition_flag'].sum()/len(df)).sort_values(ascending=False)\
    .reset_index()\
    .rename(columns={'acquisition_flag': 'acquisition_rate'})

        industry  acquisition_rate
0     Healthcare           0.00250
1    Real Estate           0.00232
2   Construction           0.00228
3         Retail           0.00218
4     Technology           0.00214
5      Logistics           0.00214
6  Manufacturing           0.00202
7    Hospitality           0.00198
8        Finance           0.00174
9      Education           0.00150

In [ ]:
#Calculating response rate for each region
(df.groupby('region')['response_flag'].sum()/len(df)).sort_values(ascending=False)\
    .reset_index()\
    .rename(columns={'response_flag': 'response_rate'})

      region  response_rate
0  Northeast        0.00680
1  Southeast        0.00674
2    Midwest        0.00632
3  Southwest        0.00632
4       West        0.00618

In [102]:
#Calculating Acquisition rate for each region
(df.groupby('region')['acquisition_flag'].sum()/len(df)).sort_values(ascending=False)\
    .reset_index()\
    .rename(columns={'acquisition_flag': 'acquisition_rate'})

      region  acquisition_rate
0  Southeast           0.00456
1  Northeast           0.00430
2  Southwest           0.00406
3       West           0.00406
4    Midwest           0.00382

In [104]:
#Calculating response rate for each business_size
(df.groupby('business_size')['response_flag'].sum()/len(df)).sort_values(ascending=False)\
    .reset_index()\
    .rename(columns={'response_flag': 'response_rate'})

     business_size  response_rate
0    Small (10-49)        0.01078
1      Micro (1-9)        0.00918
2  Medium (50-249)        0.00796
3     Large (250+)        0.00444

In [105]:
#Calculating Acquisition rate for each business_size
(df.groupby('business_size')['acquisition_flag'].sum()/len(df)).sort_values(ascending=False)\
    .reset_index()\
    .rename(columns={'acquisition_flag': 'acquisition_rate'})

     business_size  acquisition_rate
0    Small (10-49)           0.00674
1      Micro (1-9)           0.00608
2  Medium (50-249)           0.00506
3     Large (250+)           0.00292

In [106]:
#Calculating response rate for each industry offer type
(df.groupby(['industry','offer_type'])['response_flag'].sum()/len(df)).sort_values(ascending=False)\
    .reset_index()\
    .rename(columns={'response_flag': 'response_rate'})

         industry         offer_type  response_rate
0    Construction       0% Intro APR        0.00106
1      Healthcare       0% Intro APR        0.00104
2      Technology       0% Intro APR        0.00104
3       Logistics       0% Intro APR        0.00100
4   Manufacturing       0% Intro APR        0.00098
5     Real Estate       0% Intro APR        0.00098
6      Healthcare       Cash Back 2%        0.00090
7       Logistics       Cash Back 2%        0.00088
8          Retail       0% Intro APR        0.00082
9     Hospitality       Cash Back 2%        0.00082
10     Healthcare      No Annual Fee        0.00080
11   Construction       Cash Back 2%        0.00080
12        Finance       0% Intro APR        0.00080
13    Hospitality       0% Intro APR        0.00078
14    Real Estate       Cash Back 2%        0.00078
15     Technology  Rewards Points 3x        0.00074
16   Construction      No Annual Fee        0.00072
17         Retail  Rewards Points 3x        0.00070
18  Manufacturing       Cash Back 2%        0.00068
19  Manufacturing      No Annual Fee        0.00066
20      Education       0% Intro APR        0.00066
21         Retail      No Annual Fee        0.00066
22         Retail    Travel Miles 2x        0.00064
23         Retail       Cash Back 2%        0.00064
24    Real Estate      No Annual Fee        0.00064
25    Hospitality  Rewards Points 3x        0.00064
26        Finance       Cash Back 2%        0.00062
27     Technology       Cash Back 2%        0.00060
28     Healthcare  Rewards Points 3x        0.00060
29   Construction    Travel Miles 2x        0.00056
30      Logistics      No Annual Fee        0.00056
31  Manufacturing  Rewards Points 3x        0.00056
32    Real Estate  Rewards Points 3x        0.00054
33    Real Estate    Travel Miles 2x        0.00054
34        Finance    Travel Miles 2x        0.00052
35   Construction  Rewards Points 3x        0.00052
36      Education       Cash Back 2%        0.00050
37        Finance      No Annual Fee        0.00048
38    Hospitality      No Annual Fee        0.00046
39      Education      No Annual Fee        0.00046
40        Finance  Rewards Points 3x        0.00044
41      Logistics    Travel Miles 2x        0.00044
42     Technology      No Annual Fee        0.00042
43      Education    Travel Miles 2x        0.00042
44      Logistics  Rewards Points 3x        0.00042
45  Manufacturing    Travel Miles 2x        0.00042
46     Healthcare    Travel Miles 2x        0.00040
47     Technology    Travel Miles 2x        0.00038
48      Education  Rewards Points 3x        0.00032
49    Hospitality    Travel Miles 2x        0.00032

In [107]:
#Calculating Acquisition rate for each industry and offer type
(df.groupby(['industry','offer_type'])['acquisition_flag'].sum()/len(df)).sort_values(ascending=False)\
    .reset_index()\
    .rename(columns={'acquisition_flag': 'acquisition_rate'})

         industry         offer_type  acquisition_rate
0      Healthcare       0% Intro APR           0.00084
1    Construction       0% Intro APR           0.00072
2      Technology       0% Intro APR           0.00070
3     Real Estate       0% Intro APR           0.00068
4   Manufacturing       0% Intro APR           0.00064
5       Logistics       0% Intro APR           0.00064
6     Hospitality       Cash Back 2%           0.00060
7       Logistics       Cash Back 2%           0.00060
8      Healthcare       Cash Back 2%           0.00058
9     Real Estate       Cash Back 2%           0.00054
10    Hospitality       0% Intro APR           0.00052
11     Healthcare      No Annual Fee           0.00052
12         Retail       0% Intro APR           0.00052
13   Construction       Cash Back 2%           0.00050
14   Construction      No Annual Fee           0.00050
15     Technology  Rewards Points 3x           0.00048
16         Retail       Cash Back 2%           0.00048
17        Finance       0% Intro APR           0.00046
18     Technology       Cash Back 2%           0.00046
19         Retail  Rewards Points 3x           0.00042
20    Real Estate      No Annual Fee           0.00040
21  Manufacturing       Cash Back 2%           0.00040
22         Retail      No Annual Fee           0.00040
23  Manufacturing  Rewards Points 3x           0.00038
24      Education       0% Intro APR           0.00038
25  Manufacturing      No Annual Fee           0.00038
26      Education      No Annual Fee           0.00038
27      Education       Cash Back 2%           0.00036
28    Real Estate  Rewards Points 3x           0.00036
29         Retail    Travel Miles 2x           0.00036
30        Finance    Travel Miles 2x           0.00036
31    Real Estate    Travel Miles 2x           0.00034
32      Logistics      No Annual Fee           0.00034
33    Hospitality  Rewards Points 3x           0.00034
34        Finance       Cash Back 2%           0.00032
35        Finance      No Annual Fee           0.00032
36    Hospitality      No Annual Fee           0.00032
37     Healthcare  Rewards Points 3x           0.00030
38   Construction  Rewards Points 3x           0.00030
39     Technology    Travel Miles 2x           0.00030
40      Logistics  Rewards Points 3x           0.00028
41        Finance  Rewards Points 3x           0.00028
42      Logistics    Travel Miles 2x           0.00028
43     Healthcare    Travel Miles 2x           0.00026
44   Construction    Travel Miles 2x           0.00026
45  Manufacturing    Travel Miles 2x           0.00022
46    Hospitality    Travel Miles 2x           0.00020
47      Education  Rewards Points 3x           0.00020
48     Technology      No Annual Fee           0.00020
49      Education    Travel Miles 2x           0.00018

## Analysing ROI

In [135]:
#Total Mailing cost incurred
print(f'Total cost incured in mailing: ${df['mailing_cost_usd'].sum().round()}')

Total cost incured in mailing: $97470.0

In [137]:

print(f'Total charge volume generated : ${round(df['estimated_monthly_charge_volume_usd'].sum()/1000000,3)} Million')

Total charge volume generated : $21.499 Million

In [138]:
df.head()

,prospect_id,industry,business_size,region,offer_type,acquisition_channel,credit_score_band,years_in_business,mailer_sent_date,response_date,response_flag,acquisition_flag,mailing_cost_usd,estimated_monthly_charge_volume_usd,roi,cost_per_acquisition,prospect_value_tier,days_to_respond
0,100000,Education,Medium (50-249),Midwest,No Annual Fee,Lookalike Audience,700-749,1-3 yrs,2024-10-16,NaT,0,0,1.64,0.0,-1.0000,NaN,Not Acquired,NaT
1,100001,Technology,Micro (1-9),Southeast,Travel Miles 2x,Partner Referral,600-649,7-15 yrs,2023-04-25,2023-05-02,1,1,2.28,465.9,3.0868,2.28,Low Value,7 days
2,100002,Real Estate,Micro (1-9),Southwest,0% Intro APR,Cold List,750-799,3-7 yrs,2023-10-09,NaT,0,0,2.02,0.0,-1.0000,NaN,Not Acquired,NaT
3,100003,Healthcare,Large (250+),Southwest,Rewards Points 3x,Cold List,750-799,7-15 yrs,2023-09-08,NaT,0,0,2.05,0.0,-1.0000,NaN,Not Acquired,NaT
4,100004,Hospitality,Micro (1-9),Northeast,Travel Miles 2x,Cold List,700-749,<1 yr,2023-08-17,NaT,0,0,2.18,0.0,-1.0000,NaN,Not Acquired,NaT

In [ ]:
#Checking average ROI by Offer Type
df.groupby('offer_type')['roi'].mean().round(2).reset_index()\
    .rename(columns={'offer_type': 'Offer Type', 'roi': 'Average Roi'})\
    .sort_values(by='Average Roi',ascending=False)

          Offer Type  Average Roi
1       Cash Back 2%         5.93
0       0% Intro APR         5.15
2      No Annual Fee         3.97
4    Travel Miles 2x         1.43
3  Rewards Points 3x         1.35

In [151]:
#Checking average ROI by Industry
df.groupby('industry')['roi'].mean().round(2).reset_index()\
    .rename(columns={'industry': 'Industry', 'roi': 'Average Roi'})\
    .sort_values(by='Average Roi',ascending=False)

        Industry  Average Roi
0   Construction         5.11
3     Healthcare         5.05
4    Hospitality         4.45
8         Retail         3.93
9     Technology         3.41
5      Logistics         3.15
6  Manufacturing         2.98
7    Real Estate         2.93
2        Finance         2.80
1      Education         1.97

In [152]:
#Checking average ROI by Acquisition Channel
df.groupby('acquisition_channel')['roi'].mean().round(2).reset_index()\
    .rename(columns={'acquisition_channel': 'Acquisition Channel', 'roi': 'Average Roi'})\
    .sort_values(by='Average Roi',ascending=False)

  Acquisition Channel  Average Roi
0           Cold List         3.68
3        Past Inquiry         3.61
1  Lookalike Audience         3.45
2    Partner Referral         3.44

In [202]:
#Filtering only acquired customers
acquired_customers_df = df[df['acquisition_flag'] == 1]

In [163]:
acquired_customers_df.groupby('business_size')['estimated_monthly_charge_volume_usd'].mean().round(3)\
                        .reset_index()\
                        .rename(columns={'business_size': 'Business Channel Size', 'estimated_monthly_charge_volume_usd': 'Average estimated monthly charge'})

  Business Channel Size  Average estimated monthly charge
0          Large (250+)                         87948.270
1       Medium (50-249)                         24020.285
2           Micro (1-9)                          1789.736
3         Small (10-49)                          6046.882

## Waste Analysis

In [177]:
#Filtering non acquired prospects 
not_acquired_df = df[df['acquisition_flag'] == 0]

In [178]:
#Calculating total money spent on propects that were not acquired
print(f'${not_acquired_df['mailing_cost_usd'].sum()} are wasted on non-acquired prospects.')

$95469.7 are wasted on non-acquired prospects.

In [ ]:
#Calculating offer-wise money spent on non-acquired prospects
not_acquired_df.groupby('offer_type')['mailing_cost_usd'].sum().sort_values(ascending=False)

offer_type
Travel Miles 2x      22227.50
Rewards Points 3x    20407.33
0% Intro APR         19085.36
Cash Back 2%         17491.99
No Annual Fee        16257.52
Name: mailing_cost_usd, dtype: float64

In [ ]:
#Calculating industry-wise money spent on non-acquired prospects
not_acquired_df.groupby('industry')['mailing_cost_usd'].sum().sort_values(ascending=False)

industry
Real Estate      9724.76
Manufacturing    9679.63
Finance          9615.86
Education        9590.95
Logistics        9567.46
Hospitality      9471.75
Technology       9471.50
Retail           9468.12
Construction     9440.62
Healthcare       9439.05
Name: mailing_cost_usd, dtype: float64

In [181]:
#Calculating industry-wise money spent on non-acquired prospects
not_acquired_df.groupby('region')['mailing_cost_usd'].sum().sort_values(ascending=False)

region
Northeast    19537.61
Midwest      19199.94
Southwest    19175.42
Southeast    18853.28
West         18703.45
Name: mailing_cost_usd, dtype: float64

In [ ]:
not_acquired_df.groupby(['region', 'industry'])['mailing_cost_usd'].sum().reset_index()\
                .sort_values(by=['mailing_cost_usd'], ascending=False)

       region       industry  mailing_cost_usd
19  Northeast     Technology           2056.61
15  Northeast      Logistics           2044.88
34  Southwest    Hospitality           2017.86
31  Southwest      Education           1999.02
37  Southwest    Real Estate           1983.20
36  Southwest  Manufacturing           1982.01
5     Midwest      Logistics           1980.98
12  Northeast        Finance           1972.99
21  Southeast      Education           1961.96
8     Midwest         Retail           1960.12
32  Southwest        Finance           1958.24
47       West    Real Estate           1957.81
7     Midwest    Real Estate           1955.29
10  Northeast   Construction           1955.13
16  Northeast  Manufacturing           1953.18
18  Northeast         Retail           1952.62
2     Midwest        Finance           1938.74
6     Midwest  Manufacturing           1934.76
22  Southeast        Finance           1928.75
13  Northeast     Healthcare           1927.34
17  Northeast    Real Estate           1926.23
49       West     Technology           1921.42
0     Midwest   Construction           1919.36
3     Midwest     Healthcare           1915.19
46       West  Manufacturing           1911.41
11  Northeast      Education           1907.45
24  Southeast    Hospitality           1903.29
27  Southeast    Real Estate           1902.23
33  Southwest     Healthcare           1901.53
38  Southwest         Retail           1898.37
26  Southeast  Manufacturing           1898.27
41       West      Education           1889.12
30  Southwest   Construction           1887.07
9     Midwest     Technology           1882.47
4     Midwest    Hospitality           1879.63
45       West      Logistics           1878.43
23  Southeast     Healthcare           1878.24
25  Southeast      Logistics           1868.37
29  Southeast     Technology           1857.68
40       West   Construction           1852.23
14  Northeast    Hospitality           1841.18
1     Midwest      Education           1833.40
44       West    Hospitality           1829.79
48       West         Retail           1829.35
28  Southeast         Retail           1827.66
20  Southeast   Construction           1826.83
42       West        Finance           1817.14
43       West     Healthcare           1816.75
35  Southwest      Logistics           1794.80
39  Southwest     Technology           1753.32

## Pareto Analysis

In [ ]:
#Sorting the df in descenting order
acquired_customers_df = acquired_customers_df.sort_values(by='estimated_monthly_charge_volume_usd', ascending=False)

In [ ]:
#calculating cumulative percentage column in the dataframe
acquired_customers_df['cum_pct'] = (acquired_customers_df['estimated_monthly_charge_volume_usd'].cumsum()\
                                    /acquired_customers_df['estimated_monthly_charge_volume_usd'].sum()) * 100

In [231]:
customers_80_perc = len(acquired_customers_df[acquired_customers_df['cum_pct'] <= 80])
total_acquired_customers = len(acquired_customers_df)

print(f'Customers Responsible for 80% of Monthly Charge Volume: {customers_80_perc}')
print('')
print(f'Total Acquired Customers: {total_acquired_customers}')

Customers Responsible for 80% of Monthly Charge Volume: 283

Total Acquired Customers: 1040

In [232]:
print(f"{round(customers_80_perc/total_acquired_customers*100)}% of customers are responsible for 80% of Monthly Charge Volume.")

27% of customers are responsible for 80% of Monthly Charge Volume.

## Time Trend analysis

In [ ]:
#Adding year-month column to look at the trend
df['year_month'] = df['mailer_sent_date'].dt.strftime('%Y-%m')

In [253]:
summary_df = df.groupby('year_month')\
                .agg(
                    total_mailers_sent = ('mailer_sent_date', 'count'),
                    total_acquisitions = ('acquisition_flag', 'sum'),
                    total_mailing_cost = ('mailing_cost_usd', 'sum')
                ).reset_index()

In [ ]:
#Calculating monthly acquisition rate
summary_df['acquisition_rate'] = (summary_df['total_acquisitions']/summary_df['total_mailers_sent'])*100

In [258]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(
    go.Scatter(
        x=summary_df['year_month'],
        y=summary_df['total_mailers_sent'],
        name='Mailers Sent'
    ),
    secondary_y=False
)

fig.add_trace(
    go.Scatter(
        x=summary_df['year_month'],
        y=summary_df['total_acquisitions'],
        name='Acquisitions'
    ),
    secondary_y=False
)

fig.add_trace(
    go.Scatter(
        x=summary_df['year_month'],
        y=summary_df['total_mailing_cost'],
        name='Mailing Cost ($)'
    ),
    secondary_y=True
)

fig.update_layout(title='Mailer Performance by Month')

fig.show()

In [267]:
fig = px.line(
    summary_df,
    x='year_month',
    y='acquisition_rate',
    markers=True,
    title='Monthly Acquisition Rate (%)'
)

fig.update_layout(
    width=1500,
    height=600,
    xaxis_title='Month',
    yaxis_title='Acquisition Rate (%)'
)

fig.show()

In [269]:
df.to_csv('cleaned_dataset.csv')